module.exports = {
  textColor: ['responsive', 'important'],
  backgroundColor: [
    'responsive',
    'important',
    'disabled',
    'hover',
    'focus',
    'active',
    'before',
    'after',
  ],
  pointerEvents: ['responsive', 'disabled', 'hover', 'focus', 'active'],
  outline: ['focus', 'active', 'responsive'],
  borderRadius: ['responsive', 'important'],
  padding: ['responsive', 'important'],
  boxShadow: ['responsive', 'important'],
  borderColor: [
    'responsive',
    'important',
    'disabled',
    'hover',
    'focus',
    'active',
    'before',
    'after',
  ],
  margin: ['responsive', 'hover', 'focus', 'before', 'after'],
  width: ['responsive', 'hover', 'focus', 'before', 'after'],
  height: ['responsive', 'hover', 'focus', 'before', 'after'],
  rotate: [
    'responsive',
    'hover',
    'focus',
    'active',
    'group-hover',
    'before',
    'after',
  ],
  transform: ['responsive', 'hover', 'focus', 'active', 'before', 'after'],
  position: ['responsive', 'hover', 'focus', 'before', 'after'],
  zIndex: ['responsive', 'hover', 'focus', 'before', 'after'],
};
