module.exports = {
  textColor: ['responsive', 'important'],
  backgroundColor: [
    'responsive',
    'important',
    'disabled',
    'hover',
    'focus',
    'active',
  ],
  pointerEvents: ['responsive', 'disabled', 'hover', 'focus', 'active'],
  outline: ['focus', 'active', 'responsive'],
  borderRadius: ['responsive', 'important'],
  padding: ['responsive', 'important'],
  boxShadow: ['responsive', 'important'],
  borderWidth: ['responsive', 'hover', 'focus', 'before', 'after'],
  borderColor: [
    'responsive',
    'important',
    'disabled',
    'hover',
    'focus',
    'active',
    'before',
    'after',
  ],
};
