//
// This is a generated file. DO NOT EDIT IT.
// Instead run:
//
// yarn install #if you've updated @tabler/icons-react
// yarn gen:icons
//
import React from 'react';
import { CSSWithMultiValues, Icon, RecursiveCSSObject, forwardRef, useStyleConfig } from '@chakra-ui/react';
import * as Tabler from '@tabler/icons-react';
import { IconProps } from './types';

// TODO: 🚨 UPDATE THE SCRIPT TO ADD FORWARDREF TO THE ICONS, THIS FILE SHOULDNT BE UPDATED MANUALLY
const withIcon = (Component: React.FC, props: IconProps, ref?: any) => {
  const styles = useStyleConfig('Icon', { size: props?.size }) as Record<
    string,
    RecursiveCSSObject<CSSWithMultiValues>
  >;
  return (
    <Icon {...styles} {...props} ref={ref}>
      <Component />
    </Icon>
  );
};

export const IconAdjustments = (props: IconProps) => withIcon(Tabler.IconAdjustments, props);
export const IconAdjustmentsHorizontal = (props: IconProps) => withIcon(Tabler.IconAdjustmentsHorizontal, props);
export const IconAlertCircle = (props: IconProps) => withIcon(Tabler.IconAlertCircle, props);
export const IconAlertTriangle = (props: IconProps) => withIcon(Tabler.IconAlertTriangle, props);
export const IconAlignCenter = (props: IconProps) => withIcon(Tabler.IconAlignCenter, props);
export const IconAlignJustified = (props: IconProps) => withIcon(Tabler.IconAlignJustified, props);
export const IconAlignLeft = (props: IconProps) => withIcon(Tabler.IconAlignLeft, props);
export const IconAlignRight = (props: IconProps) => withIcon(Tabler.IconAlignRight, props);
export const IconArchive = (props: IconProps) => withIcon(Tabler.IconArchive, props);
export const IconArrowBackUp = (props: IconProps) => withIcon(Tabler.IconArrowBackUp, props);
export const IconArrowDown = (props: IconProps) => withIcon(Tabler.IconArrowDown, props);
export const IconArrowForwardUp = (props: IconProps) => withIcon(Tabler.IconArrowForwardUp, props);
export const IconArrowLeft = (props: IconProps) => withIcon(Tabler.IconArrowLeft, props);
export const IconArrowRight = (props: IconProps) => withIcon(Tabler.IconArrowRight, props);
export const IconArrowUp = (props: IconProps) => withIcon(Tabler.IconArrowUp, props);
export const IconArrowsMaximize = (props: IconProps) => withIcon(Tabler.IconArrowsMaximize, props);
export const IconArrowsMinimize = (props: IconProps) => withIcon(Tabler.IconArrowsMinimize, props);
export const IconArrowsSort = (props: IconProps) => withIcon(Tabler.IconArrowsSort, props);
export const IconBan = (props: IconProps) => withIcon(Tabler.IconBan, props);
export const IconBell = (props: IconProps) => withIcon(Tabler.IconBell, props);
export const IconBellOff = (props: IconProps) => withIcon(Tabler.IconBellOff, props);
export const IconBold = (props: IconProps) => withIcon(Tabler.IconBold, props);
export const IconBookmark = (props: IconProps) => withIcon(Tabler.IconBookmark, props);
export const IconBookmarkOff = (props: IconProps) => withIcon(Tabler.IconBookmarkOff, props);
export const IconBrandFacebook = (props: IconProps) => withIcon(Tabler.IconBrandFacebook, props);
export const IconBrandInstagram = (props: IconProps) => withIcon(Tabler.IconBrandInstagram, props);
export const IconBrandLinkedin = (props: IconProps) => withIcon(Tabler.IconBrandLinkedin, props);
export const IconBrandTwitter = (props: IconProps) => withIcon(Tabler.IconBrandTwitter, props);
export const IconBrandX = (props: IconProps) => withIcon(Tabler.IconBrandX, props);
export const IconCalendar = (props: IconProps) => withIcon(Tabler.IconCalendar, props);
export const IconCalendarEvent = (props: IconProps) => withIcon(Tabler.IconCalendarEvent, props);
export const IconCamera = (props: IconProps) => withIcon(Tabler.IconCamera, props);
export const IconCameraPlus = (props: IconProps) => withIcon(Tabler.IconCameraPlus, props);
export const IconCaretDown = (props: IconProps) => withIcon(Tabler.IconCaretDown, props);
export const IconCaretLeft = (props: IconProps) => withIcon(Tabler.IconCaretLeft, props);
export const IconCaretRight = (props: IconProps) => withIcon(Tabler.IconCaretRight, props);
export const IconCaretUp = (props: IconProps) => withIcon(Tabler.IconCaretUp, props);
export const IconCheck = (props: IconProps) => withIcon(Tabler.IconCheck, props);
export const IconChevronDown = forwardRef((props: IconProps, ref) => withIcon(Tabler.IconChevronDown, props, ref));
export const IconChevronLeft = (props: IconProps) => withIcon(Tabler.IconChevronLeft, props);
export const IconChevronRight = (props: IconProps) => withIcon(Tabler.IconChevronRight, props);
export const IconChevronUp = (props: IconProps) => withIcon(Tabler.IconChevronUp, props);
export const IconCircle0 = (props: IconProps) => withIcon(Tabler.IconCircleNumber0, props);
export const IconCircle1 = (props: IconProps) => withIcon(Tabler.IconCircleNumber1, props);
export const IconCircle2 = (props: IconProps) => withIcon(Tabler.IconCircleNumber2, props);
export const IconCircle3 = (props: IconProps) => withIcon(Tabler.IconCircleNumber3, props);
export const IconCircle4 = (props: IconProps) => withIcon(Tabler.IconCircleNumber4, props);
export const IconCircle5 = (props: IconProps) => withIcon(Tabler.IconCircleNumber5, props);
export const IconCircle6 = (props: IconProps) => withIcon(Tabler.IconCircleNumber6, props);
export const IconCircle7 = (props: IconProps) => withIcon(Tabler.IconCircleNumber7, props);
export const IconCircle8 = (props: IconProps) => withIcon(Tabler.IconCircleNumber8, props);
export const IconCircle9 = (props: IconProps) => withIcon(Tabler.IconCircleNumber9, props);
export const IconCircleCheck = (props: IconProps) => withIcon(Tabler.IconCircleCheck, props);
export const IconCircleCheckFilled = (props: IconProps) => withIcon(Tabler.IconCircleCheckFilled, props);
export const IconCircleMinus = (props: IconProps) => withIcon(Tabler.IconCircleMinus, props);
export const IconCirclePlus = (props: IconProps) => withIcon(Tabler.IconCirclePlus, props);
export const IconCircleX = (props: IconProps) => withIcon(Tabler.IconCircleX, props);
export const IconClock = (props: IconProps) => withIcon(Tabler.IconClock, props);
export const IconCloud = (props: IconProps) => withIcon(Tabler.IconCloud, props);
export const IconCloudDownload = (props: IconProps) => withIcon(Tabler.IconCloudDownload, props);
export const IconCloudOff = (props: IconProps) => withIcon(Tabler.IconCloudOff, props);
export const IconCloudUpload = (props: IconProps) => withIcon(Tabler.IconCloudUpload, props);
export const IconCode = (props: IconProps) => withIcon(Tabler.IconCode, props);
export const IconCoin = (props: IconProps) => withIcon(Tabler.IconCoin, props);
export const IconCreditCard = (props: IconProps) => withIcon(Tabler.IconCreditCard, props);
export const IconCurrentLocation = (props: IconProps) => withIcon(Tabler.IconCurrentLocation, props);
export const IconDeviceDesktop = (props: IconProps) => withIcon(Tabler.IconDeviceDesktop, props);
export const IconDeviceMobile = (props: IconProps) => withIcon(Tabler.IconDeviceMobile, props);
export const IconDeviceTablet = (props: IconProps) => withIcon(Tabler.IconDeviceTablet, props);
export const IconDots = (props: IconProps) => withIcon(Tabler.IconDots, props);
export const IconDownload = (props: IconProps) => withIcon(Tabler.IconDownload, props);
export const IconEdit = (props: IconProps) => withIcon(Tabler.IconEdit, props);
export const IconExternalLink = (props: IconProps) => withIcon(Tabler.IconExternalLink, props);
export const IconEye = (props: IconProps) => withIcon(Tabler.IconEye, props);
export const IconEyeOff = (props: IconProps) => withIcon(Tabler.IconEyeOff, props);
export const IconFile = (props: IconProps) => withIcon(Tabler.IconFile, props);
export const IconFileDownload = (props: IconProps) => withIcon(Tabler.IconFileDownload, props);
export const IconFileExport = (props: IconProps) => withIcon(Tabler.IconFileExport, props);
export const IconFileImport = (props: IconProps) => withIcon(Tabler.IconFileImport, props);
export const IconFileSearch = (props: IconProps) => withIcon(Tabler.IconFileSearch, props);
export const IconFileUpload = (props: IconProps) => withIcon(Tabler.IconFileUpload, props);
export const IconFiles = (props: IconProps) => withIcon(Tabler.IconFiles, props);
export const IconFilter = (props: IconProps) => withIcon(Tabler.IconFilter, props);
export const IconFingerprint = (props: IconProps) => withIcon(Tabler.IconFingerprint, props);
export const IconFlag = (props: IconProps) => withIcon(Tabler.IconFlag, props);
export const IconFolder = (props: IconProps) => withIcon(Tabler.IconFolder, props);
export const IconFolderOff = (props: IconProps) => withIcon(Tabler.IconFolderOff, props);
export const IconFolderPlus = (props: IconProps) => withIcon(Tabler.IconFolderPlus, props);
export const IconFolderX = (props: IconProps) => withIcon(Tabler.IconFolderX, props);
export const IconH1 = (props: IconProps) => withIcon(Tabler.IconH1, props);
export const IconH2 = (props: IconProps) => withIcon(Tabler.IconH2, props);
export const IconH3 = (props: IconProps) => withIcon(Tabler.IconH3, props);
export const IconH4 = (props: IconProps) => withIcon(Tabler.IconH4, props);
export const IconH5 = (props: IconProps) => withIcon(Tabler.IconH5, props);
export const IconH6 = (props: IconProps) => withIcon(Tabler.IconH6, props);
export const IconHash = (props: IconProps) => withIcon(Tabler.IconHash, props);
export const IconHeart = (props: IconProps) => withIcon(Tabler.IconHeart, props);
export const IconHelp = (props: IconProps) => withIcon(Tabler.IconHelp, props);
export const IconInbox = (props: IconProps) => withIcon(Tabler.IconInbox, props);
export const IconInfoCircle = (props: IconProps) => withIcon(Tabler.IconInfoCircle, props);
export const IconItalic = (props: IconProps) => withIcon(Tabler.IconItalic, props);
export const IconLayout = (props: IconProps) => withIcon(Tabler.IconLayout, props);
export const IconLetterT = (props: IconProps) => withIcon(Tabler.IconLetterT, props);
export const IconLink = (props: IconProps) => withIcon(Tabler.IconLink, props);
export const IconList = (props: IconProps) => withIcon(Tabler.IconList, props);
export const IconListNumbers = (props: IconProps) => withIcon(Tabler.IconListNumbers, props);
export const IconLocation = (props: IconProps) => withIcon(Tabler.IconLocation, props);
export const IconLock = (props: IconProps) => withIcon(Tabler.IconLock, props);
export const IconLockOpen = (props: IconProps) => withIcon(Tabler.IconLockOpen, props);
export const IconLogin = (props: IconProps) => withIcon(Tabler.IconLogin, props);
export const IconLogout = (props: IconProps) => withIcon(Tabler.IconLogout, props);
export const IconMail = (props: IconProps) => withIcon(Tabler.IconMail, props);
export const IconMailOpened = (props: IconProps) => withIcon(Tabler.IconMailOpened, props);
export const IconMap = (props: IconProps) => withIcon(Tabler.IconMap, props);
export const IconMapPin = (props: IconProps) => withIcon(Tabler.IconMapPin, props);
export const IconMarkdown = (props: IconProps) => withIcon(Tabler.IconMarkdown, props);
export const IconMenu2 = (props: IconProps) => withIcon(Tabler.IconMenu2, props);
export const IconMessage = (props: IconProps) => withIcon(Tabler.IconMessage, props);
export const IconMicrophone = (props: IconProps) => withIcon(Tabler.IconMicrophone, props);
export const IconMicrophoneOff = (props: IconProps) => withIcon(Tabler.IconMicrophoneOff, props);
export const IconMusic = (props: IconProps) => withIcon(Tabler.IconMusic, props);
export const IconPaperclip = (props: IconProps) => withIcon(Tabler.IconPaperclip, props);
export const IconPencil = (props: IconProps) => withIcon(Tabler.IconPencil, props);
export const IconPhone = (props: IconProps) => withIcon(Tabler.IconPhone, props);
export const IconPhoneIncoming = (props: IconProps) => withIcon(Tabler.IconPhoneIncoming, props);
export const IconPhoneOff = (props: IconProps) => withIcon(Tabler.IconPhoneOff, props);
export const IconPhoneOutgoing = (props: IconProps) => withIcon(Tabler.IconPhoneOutgoing, props);
export const IconPhoto = (props: IconProps) => withIcon(Tabler.IconPhoto, props);
export const IconPin = (props: IconProps) => withIcon(Tabler.IconPin, props);
export const IconPinnedOff = (props: IconProps) => withIcon(Tabler.IconPinnedOff, props);
export const IconPlayerPause = (props: IconProps) => withIcon(Tabler.IconPlayerPause, props);
export const IconPlayerPlay = (props: IconProps) => withIcon(Tabler.IconPlayerPlay, props);
export const IconPlayerRecord = (props: IconProps) => withIcon(Tabler.IconPlayerRecord, props);
export const IconPlayerSkipBack = (props: IconProps) => withIcon(Tabler.IconPlayerSkipBack, props);
export const IconPlayerSkipForward = (props: IconProps) => withIcon(Tabler.IconPlayerSkipForward, props);
export const IconPlayerStop = (props: IconProps) => withIcon(Tabler.IconPlayerStop, props);
export const IconPlayerTrackNext = (props: IconProps) => withIcon(Tabler.IconPlayerTrackNext, props);
export const IconPlayerTrackPrev = (props: IconProps) => withIcon(Tabler.IconPlayerTrackPrev, props);
export const IconPlus = (props: IconProps) => withIcon(Tabler.IconPlus, props);
export const IconRadiusBottomLeft = (props: IconProps) => withIcon(Tabler.IconRadiusBottomLeft, props);
export const IconRefresh = (props: IconProps) => withIcon(Tabler.IconRefresh, props);
export const IconSearch = (props: IconProps) => withIcon(Tabler.IconSearch, props);
export const IconSelector = (props: IconProps) => withIcon(Tabler.IconSelector, props);
export const IconSend = (props: IconProps) => withIcon(Tabler.IconSend, props);
export const IconSettings = (props: IconProps) => withIcon(Tabler.IconSettings, props);
export const IconShare = (props: IconProps) => withIcon(Tabler.IconShare, props);
export const IconShield = (props: IconProps) => withIcon(Tabler.IconShield, props);
export const IconShoppingCart = (props: IconProps) => withIcon(Tabler.IconShoppingCart, props);
export const IconSourceCode = (props: IconProps) => withIcon(Tabler.IconSourceCode, props);
export const IconStar = (props: IconProps) => withIcon(Tabler.IconStar, props);
export const IconStrikethrough = (props: IconProps) => withIcon(Tabler.IconStrikethrough, props);
export const IconTag = (props: IconProps) => withIcon(Tabler.IconTag, props);
export const IconThumbDown = (props: IconProps) => withIcon(Tabler.IconThumbDown, props);
export const IconThumbUp = (props: IconProps) => withIcon(Tabler.IconThumbUp, props);
export const IconTrash = (props: IconProps) => withIcon(Tabler.IconTrash, props);
export const IconUnderline = (props: IconProps) => withIcon(Tabler.IconUnderline, props);
export const IconUpload = (props: IconProps) => withIcon(Tabler.IconUpload, props);
export const IconUser = (props: IconProps) => withIcon(Tabler.IconUser, props);
export const IconUserCircle = (props: IconProps) => withIcon(Tabler.IconUserCircle, props);
export const IconUsers = (props: IconProps) => withIcon(Tabler.IconUsers, props);
export const IconVideo = (props: IconProps) => withIcon(Tabler.IconVideo, props);
export const IconVideoOff = (props: IconProps) => withIcon(Tabler.IconVideoOff, props);
export const IconVolume = (props: IconProps) => withIcon(Tabler.IconVolume, props);
export const IconVolume2 = (props: IconProps) => withIcon(Tabler.IconVolume2, props);
export const IconVolume3 = (props: IconProps) => withIcon(Tabler.IconVolume3, props);
export const IconWorld = (props: IconProps) => withIcon(Tabler.IconWorld, props);
export const IconX = (props: IconProps) => withIcon(Tabler.IconX, props);
export const IconZoomIn = (props: IconProps) => withIcon(Tabler.IconZoomIn, props);
export const IconZoomOut = (props: IconProps) => withIcon(Tabler.IconZoomOut, props);
