name: "Chromatic"
on: 'push'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install modules
      run: npm install
    - name: Build storybook
      run: npm run build-storybook
    - uses: chromaui/action@v10
      with:
        appCode: ${{ secrets.CHROMATIC_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
        storybookBuildDir: "./projects/ui-storybook/storybook-static"
        autoAcceptChanges: "master"
