name: 'Chromatic'
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - uses: chromaui/action@v1
      with:
        appCode: cc7b1csiu9
        token: ${{ secrets.GITHUB_TOKEN }}
        storybookBuildDir: "./packages/components/storybook-static"
