name: Build and Deploy to Cloud Run
on: 
  push:
    branches:
    - master
    - deploy

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1

jobs:
  setup-build-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1

    - name: Copy deploy files to root
      run: cp -r ./deploy/storybook/. ./

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --timeout=1200s \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/storybook-${GITHUB_REF##*/}:$GITHUB_SHA" .

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy storybook-${GITHUB_REF##*/} \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/storybook-${GITHUB_REF##*/}:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
