name: 'Linter'
on: 'push'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run linter
      run: yarn lint
    - name: Run type check
      run: yarn type:check
